### ISSUE TITLE
Point cloud file

### ISSUE THREAD

**Issue by kwea123** [yhw-yhw/PVAMVSNet#2]
Hi, I cannot download from baiduyun. Can you put the [files](https://pan.baidu.com/s/1R3loCM8pcNEWMfB14BUyNg) on google drive or github release, or can you send to my email? Thank you.

**Comment by yhw-yhw** [comment]
https://1drv.ms/u/s!AoPEu_jRzSFtbfXAVq_Do_30xTQ?e=V8QGAn
